### ISSUE TITLE
Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by marcreichel** [dominique-mueller/angular-package-builder#96]
Hi,

when I try to build my angular project as a package I get this error in the "Prepare (line breaks, resources)"-step. My project is an Angular Project with SCSS-Styles (if this matters?).

Any ideas how to fix this?

**Comment by dominique-mueller** [comment]
Can you share the repository, or is it internal?

Also:
- Do you use styleUrls for your SASS files?
- Do you use relative URLs as styleUrls?
- Can you identify a specific component this fails with?

**Comment by marcreichel** [comment]
It is an internal repository.

- Yes, I use relative styleUrls within the components
- I‘ve just started a completely new project with the angular-cli so it must be the default app component

**Comment by dominique-mueller** [comment]
That's weird, the integration tests are based on a default Angular app created with the CLI. What versions of Angular & Angular CLI are you using? Any chance you could create a repo reproducing the issue?

**Comment by marcreichel** [comment]
I‘ll lookup the versions at work tomorrow.
I‘ll also try to create a repository to reproduce the issue tomorrow.

**Comment by marcreichel** [comment]
My versions are:

Angular **5.2.10**
Angular CLI **1.7.4**

I'm on Windows 10, if that helps?

Here's a Repository I freshly generated via Angular CLI and there's the same problem:
https://github.com/marcreichel/Angular-Package

Might it be an issue that I've set up SCSS manually?

**Comment by dominique-mueller** [comment]
Ok, after some analysis I found out that the issue occurs when the styles file is empty. Adding something (even if it's just a comment) fixes the situation. That's definitely a bug to be fixed.

**Comment by dominique-mueller** [comment]
The resulting bundles will be empty, though. But that's only logical, cause you're trying to build an application - not a library. The Angular Package Builder only builds libraries.

I wonder what's your exact use case here? Usually, a repo only contains the library. Sometimes, a repo might also contain some kind of demo application. In such a use case, I'd recommend to have separate `app` and `lib` folders, and use the Angular CLI to build the `app` folder and the Angular Package Builder to build the `lib` folder.

**Comment by marcreichel** [comment]
Oh, okay. Thanks for the help.

Well, I thought your package-builder builds an angular-package out of an angular-application. Nevermind 👍 Then I will code the library itself in a separate project 😄

**Comment by dominique-mueller** [comment]
Alright, let me know when you're facing any other issue. Nevertheless, you were still able to discover an interesting bug, so thanks for that! :+1:
